apiVersion: v1
kind: Service
metadata:
  name: server-app-service
spec:
  selector:
    app: server-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: server-app
  labels:
    app: server-app
    name: server-app
spec:
  containers:
  - name: server-app
    image: server-image
    imagePullPolicy: Never
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
